<?php if($this->showDescription == true): ?>
<h2>Complete Download Service</h2>
<h3>Description</h3>
<p>
	Retrieves the URL of a zipped archive containing information about all taxa.
</p>

<h3>Usage</h3>
<p>
	Use the following syntax to query this web service:
	http://<?php echo $_SERVER['HTTP_HOST'];?><?php echo $this->baseUrl; ?>completedownloadservice/key/[key]/version/[version].
	A key is required. A version is optional, to know witch versions are available, use the List Releases webservice. An example is:
	http://<?php echo $_SERVER['HTTP_HOST'];?><?php echo $this->baseUrl; ?>completedownloadservice/key/740d4b20592c631d226488f5455d4cb6/version/1 January 2012
</p>
<p>
	The web service will return the URL that is available to download.
</p>
<?php else: ?>
<?php echo $this->xmlheader; ?>

<sp2000>
	<request>
		<service id='fulldownloadservice'></service>
		<description>
			i4Life download service to retrieve the Catalogue of Life
			as DwC-a file.
		</description>
		<parameters>
<?php foreach($this->params as $param => $value): ?>
			<<?php echo $param; ?>><?php echo $value; ?></<?php echo $param; ?>>
<?php endforeach; ?>
		</parameters>
		<date><?php echo $this->date; ?></date>
		<catalogue_version><?php echo $this->version; ?></catalogue_version>
	</request>
	<response>
<?php if(isset($this->error)): ?>
		<error><?php echo $this->error; ?></error>
<?php else: ?>
		<downloadurl><?php echo $this->url; ?></downloadurl>
		<size><?php echo $this->size; ?></size>
<?php endif; ?>
	</response>
<?php if(!isset($this->error)): ?>
	<status code='0'>Success</status>
<?php endif; ?>
</sp2000>
<?php endif; ?>