<h2>Welcome</h2>
<p>
	 Welcome to Download Service 1.2 of the Catalogue of Life. Here you can find
    information on how to interact with the web service.
</p>

<h2>Subscribing</h2>
<p>
	When calling our web services, your application must provide a key as part
	of the service URL. You can obtain a key by filling out the form below. Anyone
	can make use of the web services provided by the Catalogue of Life. However, we
	reserve the right to suspend, terminate or change the terms of your use of the
	services at any time.
</p>

<p>
	We need at least the domain from which you will be calling our services. The
	key will work for the domain you enter and all its subdomains. You can optionally
	provide us with an email address, so which can inform you about upcoming changes
	in the API, server malfunctions, etc. etc.
</p>

<p>
	<form method="post">
		<table>
			<tbody id="keyform-container">
    			<tr>
    				<td class="right-aligned">Your Domain *</td>
    				<td><input id="domain" type="text" name="domain" value="<?php echo $_SERVER['REMOTE_ADDR'];?>" style="width:300px;" /></td>
    			</tr>
    			<tr>
    				<td class="right-aligned">Your Email</td>
    				<td><input id="email" type="text" name="email" style="width:300px;" /></td>
    			</tr>
    		</tbody>
		</table>
		<div id="button-container0">
			<button type="button" onclick="generateKey();">Generate key</button>
		</div>
	</form>
</p>

<h2>Partial Download Service</h2>
<h3>Description</h3>
<p>
	Retrieves the URL of a zipped archive containing information about a current taxon
	and its children. The web service can give three export or block options.
</p>

<h3>Field set options</h3>
<p>
	Classification only: Exports the higher classification exclusively, without
	species. Just from toplevelgroup (or any selected taxa) down to genus.
</p>
<p>
	Limited data: Exports accepted scientific name linked to references,
	synonym(s) linked to reference(s), latest taxonomic scrutiny, source database and
	Catalogue of Life edition, classification above genus and LSID.
</p>
<p>
	Complete data: Exports fields as defined under 'Limited data', plus common
	name(s) linked to reference(s), distribution, life zone and additional data.
</p>

<h3>Usage</h3>
<p>
	Use the following syntax to query this web service:
	[domain]/partialdownloadservice/[loop][rank]/[taxonName]/[endLoop]/field_set/[fieldSet]/key/[key].
	The domain is required, this is the domain of the webservice. The following ranks are allowed: kingdom, phylum, class, order, superfamily, family
	and genus. The following field sets are allowed: classification_only (default), limited_data, complete_data. A key is required. An example is:
	http://dev.4d4life.eu/DS1.2/partialdownloadservice/toplevelgroup/Animalia/phylum/Chordata/class/Aves/field_set/limited/key/740d4b20592c631d226488f5455d4cb6
</p>
<p>
	The web service will return the URL that is/or will be available to download, plus a
	boolean whether the URL is already accessible. As the zip file can take some time to
	create, you will have to poll the web service from time to time to check if the zip
	file has been created and the URL is accessible.
</p>

<h2>Complete Download Service</h2>
<h3>Description</h3>
<p>
	Retrieves the URL of a zipped archive containing information about all taxa.
</p>

<h3>Usage</h3>
<p>
	Use the following syntax to query this web service:
	[domain]/completedownloadservice/key/[key]/version/[version].
	The domain is required, this is the domain of the webservice. A key is required. A version is optional, to know witch versions are available, use the List Releases webservice. An example is:
	http://dev.4d4life.eu/DS1.2/completedownloadservice/key/740d4b20592c631d226488f5455d4cb6/version/1 January 2012
</p>
<p>
	The web service will return the URL that is available to download.
</p>

<h2>List Releases</h2>
<h3>Description</h3>
<p>
	Retrieves the URLs, the size and version of zipped archives containing information about the full database.
</p>

<h3>Usage</h3>
<p>
	Use the following syntax to query this web service:
	[domain]/listreleases/key/[key]. A key is required. An example is:
	The domain is required, this is the domain of the webservice. A key is required.
	http://dev.4d4life.eu/DS1.2/listreleases/key/740d4b20592c631d226488f5455d4cb6
</p>
