<?php if($this->showDescription == true): ?>
<h2>List Releases</h2>
<h3>Description</h3>
<p>
	Retrieves the URLs, the size and version of zipped archives containing information about the full database.
</p>

<h3>Usage</h3>
<p>
	Use the following syntax to query this web service:
	http://<?php echo $_SERVER['HTTP_HOST'];?><?php echo $this->baseUrl; ?>/listreleases/key/[key]. A key is required. An example is:
	http://<?php echo $_SERVER['HTTP_HOST'];?><?php echo $this->baseUrl; ?>/listreleases/key/740d4b20592c631d226488f5455d4cb6
</p>

<? else: ?>
<?php echo $this->xmlheader; ?>

<sp2000>
	<request>
		<service id='getversions'></service>
		<description>
			i4Life download service to retrieve the versions available for download.
		</description>
		<parameters>
<?php foreach($this->params as $param => $value): ?>
			<<?php echo $param; ?>><?php echo $value; ?></<?php echo $param; ?>>
<?php endforeach; ?>
		</parameters>
		<date><?php echo $this->date; ?></date>
	</request>
	<response>
<?php if(isset($this->error)): ?>
		<error><?php echo $this->error; ?></error>
<?php else: ?>
		<versions>
<?php foreach ($this->versions as $version): ?>
			<version><?php echo $version['edition']; ?></version>
<?php endforeach; ?>
		</versions>
<?php endif; ?>
	</response>
<?php if(!isset($this->error)): ?>
	<status code='0'>Success</status>
<?php endif; ?>
</sp2000>
<?php endif; ?>